# Generated by Django 3.0.9 on 2020-08-08 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message=" format: '+911234567890','01234567890','1234567890' Up to 12 digits allowed.", regex='^\\+?\\d{10,10}$')]),
        ),
    ]
