# Generated by Django 3.0.9 on 2020-08-08 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200808_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message=" format: '1234567890','1234567890','1234567890' Up to 10 digits allowed.", regex='^\\+?\\d{10,10}$')]),
        ),
    ]
